#!/usr/bin/env bash

# Set environment variables for dev
export WWW_PORT=${WWW_PORT:-80}
export DB_PORT=${DB_PORT:-3306}
export DB_ROOT_USER=${DB_ROOT_USER:-root}
export DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
export DB_NAME=${DB_NAME:-test3}
export DB_USER=${DB_USER:-test3}
export DB_PASSWORD=${DB_PASSWORD:-test3}

# docker-compose command
COMPOSE="docker-compose"

# working director
WORKINGDIR="/var/www/html"

# machine names from docker-compose.yml
WWWSERVER="webserver"
NODE="node"
MYSQL="mysql"
REDIS="redis"

# If we pass any arguments...
if [ $# -gt 0 ];then

    # If "art" is used, pass-thru to "artisan"
    # inside a new container
    if [ "$1" == "artisan" ]; then
        shift 1
        $COMPOSE run --rm \
            -w $WORKINGDIR \
            $WWWSERVER \
            php artisan "$@"

    # If "composer" is used, pass-thru to "composer"
    # inside a new container
    elif [ "$1" == "composer" ]; then
        shift 1
        $COMPOSE run --rm \
            -w $WORKINGDIR \
            $WWWSERVER \
            composer "$@"

    # If "test" is used, run unit tests,
    # pass-thru any extra arguments to php-unit
    elif [ "$1" == "test" ]; then
        shift 1
        $COMPOSE run --rm \
            -w $WORKINGDIR \
            $WWWSERVER \
            ./vendor/bin/phpunit "$@"

    # If "npm" is used, run npm
    # from our node container
    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm \
            -w $WORKINGDIR \
            $NODE \
            npm "$@"

    # If "gulp" is used, run gulp
    # from our node container
    elif [ "$1" == "gulp" ]; then
        shift 1
        $COMPOSE run --rm \
            -w $WORKINGDIR \
            $NODE \
            ./node_modules/.bin/gulp "$@"

    # If "mysql" is used, run mysql
    # from our mysql container
    elif [ "$1" == "mysql" ]; then
        shift 1
        $COMPOSE exec \
            $MYSQL \
            mysql -u$DB_ROOT_USER -p$DB_ROOT_PASSWORD "$@"

    # If "mysqldump" is used, run mysqldump
    # from our mysql container
    elif [ "$1" == "mysqldump" ]; then
        shift 1
        $COMPOSE exec \
            $MYSQL \
            mysqldump -u$DB_ROOT_USER -p$DB_ROOT_PASSWORD "$@"

    # Else, pass-thru args to docker-compose
    else
        $COMPOSE "$@"
    fi

else
    $COMPOSE ps
fi
