version: '2'
services:
    fpm:
        build:
            context: ./docker/fpm
            dockerfile: Dockerfile
        image: petehanson/fpm
        volumes:
            - ./code:/var/www/html
        networks:
            - test4

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: petehanson/nginx
        volumes:
            - ./code:/var/www/html
        ports:
            - "80:80"
        networks:
            - test4

    mysql:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        image: petehanson/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "test4"
            MYSQL_USER: "test4"
            MYSQL_PASSWORD: "test4"
        volumes:
            - test4data:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d
        networks:
            - test4

    redis:
        image: redis:alpine
        volumes:
            - test4_redisdata:/data
        networks:
            - test4

    composer:
        image: composer/composer
        volumes:
            - ./code:/app
        networks:
            - test4

    node:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        image: petehanson/node
        volumes:
            - ./code:/var/www/html
        networks:
            - test4

networks:
    test4:
        driver: "bridge"
volumes:
    test4data:
        driver: "local"
    test4_redisdata:
        driver: "local"
