version: '2'
services:
    webserver:
        build:
            context: ./docker/webserver
            dockerfile: Dockerfile
        image: petehanson/webserver
        volumes:
            - ./code:/var/www/html
        ports:
            - "${WWW_PORT}:80"
        networks:
            - test3
    node:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        image: petehanson/node
        volumes:
            - ./code:/var/www/html
        networks:
            - test3
    mysql:
        image: mysql:5.7
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - test3
    redis:
        image: redis:alpine
        volumes:
            - redisdata:/data
        networks:
            - test3
networks:
    test3:
        driver: "bridge"
volumes:
    mysqldata:
        driver: "local"
    redisdata:
        driver: "local"
