version: '2'
services:
    fpm:
        build:
            context: ./docker/fpm
            dockerfile: Dockerfile
        image: petehanson/fpm
        volumes:
            - ./code:/var/www/html
        networks:
            - test4_network

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: petehanson/nginx
        volumes:
            - ./code:/var/www/html
        ports:
            - "80:80"
            - "443:443"
        networks:
            - test4_network

    mysql:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        image: petehanson/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "test4"
            MYSQL_USER: "test4"
            MYSQL_PASSWORD: "test4"
        volumes:
            - test4_mysql_data:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d
        networks:
            - test4_network

    redis:
        image: redis:3.2
        volumes:
            - test4_redis_data:/data
        networks:
            - test4_network

    composer:
        image: composer/composer
        volumes:
            - ./code:/app
        networks:
            - test4_network

    node:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        image: petehanson/node
        volumes:
            - ./code:/var/www/html
        networks:
            - test4_network

networks:
    test4_network:
        driver: "bridge"
volumes:
    test4_mysql_data:
        driver: "local"
    test4_redis_data:
        driver: "local"
